# Generated by Django 2.0.2 on 2018-04-19 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('readCount', models.IntegerField(blank=True, default=0, verbose_name='読書回数')),
                ('editer', models.CharField(blank=True, max_length=255, verbose_name='登録者')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='bookmanager.Book', verbose_name='書籍')),
            ],
            options={
                'db_table': 'impression',
            },
        ),
    ]
