# Generated by Django 2.2 on 2018-08-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='大カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='中カテゴリ名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BigCategory', verbose_name='大カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BigCategory', verbose_name='大カテゴリ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='中カテゴリ')),
            ],
        ),
    ]
