# Generated by Django 2.0.7 on 2018-07-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='備考'),
        ),
    ]
