# Generated by Django 2.0.7 on 2018-07-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_auto_20180731_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='memo',
            field=models.CharField(default=1, max_length=50, verbose_name='備考'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='概要'),
        ),
    ]
