# Generated by Django 2.0.7 on 2018-08-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_auto_20180731_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='register',
            field=models.CharField(default=1, max_length=50, verbose_name='登録者'),
            preserve_default=False,
        ),
    ]
