# Generated by Django 2.0.7 on 2018-08-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0005_schedule_largeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='memo',
            field=models.CharField(blank=True, max_length=50, verbose_name='備考'),
        ),
    ]
