# Generated by Django 2.0.7 on 2018-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0006_auto_20180802_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.CharField(choices=[('HMK・旧シス対応', 'HMK・旧シス対応'), ('サービス対応', 'サービス対応'), ('抽出', '抽出'), ('PJT/案件', 'PJT/案件'), ('運用', '運用'), ('障害対応', '障害対応'), ('各種資料作成・入力', '各種資料作成・入力')], default='HMK・旧シス対応', max_length=50, verbose_name='大項目'),
        ),
    ]
