# Generated by Django 2.0.7 on 2018-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0007_auto_20180802_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='kosu',
            field=models.IntegerField(blank=True, verbose_name='時間(分)'),
        ),
    ]
