# Generated by Django 2.0.7 on 2018-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0009_auto_20180802_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='kosu',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間'),
        ),
    ]
