# Generated by Django 2.0.7 on 2018-08-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0010_auto_20180802_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.CharField(blank=True, max_length=50, verbose_name='大項目'),
        ),
    ]
