# Generated by Django 2.0.7 on 2018-08-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0011_auto_20180803_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.CharField(blank=True, choices=[('HMK・旧シス対応', 'HMK・旧シス対応'), ('サービス対応', 'サービス対応'), ('抽出', '抽出'), ('PJT/案件', 'PJT/案件'), ('運用', '運用'), ('障害対応', '障害対応'), ('各種資料作成・入力', '各種資料作成・入力')], max_length=50, verbose_name='大項目'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='kosu',
            field=models.IntegerField(blank=True, verbose_name='時間(分)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(blank=True, max_length=50, verbose_name='概要'),
        ),
    ]
