# Generated by Django 2.0.7 on 2018-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0014_auto_20180803_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='totalkosu',
            field=models.IntegerField(blank=True, default=0, verbose_name='総時間（分）'),
        ),
    ]
