# Generated by Django 2.0.7 on 2018-08-14 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0015_schedule_totalkosu'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='MiddleItem',
            field=models.CharField(blank=True, max_length=50, verbose_name='中項目'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='SmallItems',
            field=models.CharField(blank=True, max_length=50, verbose_name='小項目'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.CharField(blank=True, max_length=50, verbose_name='大項目'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
    ]
