# Generated by Django 2.0.7 on 2018-08-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0018_auto_20180814_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='大項目')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='中項目')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='MiddleItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.MiddleItem', verbose_name='中項目'),
        ),
    ]
