# Generated by Django 2.0.7 on 2018-08-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0019_auto_20180816_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.ForeignKey(db_column='大項目', on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='kosu',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='時間（分）'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='totalkosu',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='総時間（分）'),
        ),
    ]
