# Generated by Django 2.0.7 on 2018-08-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0020_auto_20180816_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='LargeItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目'),
        ),
    ]
