# Generated by Django 2.0.2 on 2018-04-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='impression',
            table='impression',
        ),
    ]
