# Generated by Django 2.0.2 on 2018-04-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmgr', '0002_auto_20180424_1102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='impression',
            table=None,
        ),
    ]
